# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "playground-devops-challenges-use1-tfstates-s3"
    dynamodb_table = "playground-devops-challenges-use1-tfstates-s3-lock"
    encrypt        = true
    key            = "devops/terragrunt/s3-test/terraform.tfstate"
    profile        = ""
    region         = "us-east-1"
  }
}
