apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nakama
  name: nakama
spec:
  ports:
    - name: "7349"
      port: 7349
      targetPort: 7349
    - name: "7350"
      port: 7350
      targetPort: 7350
    - name: "7451"
      port: 7451
      targetPort: 7451
  selector:
    io.kompose.service: nakama
status:
  loadBalancer: {}