apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cockroachdb
  name: cockroachdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cockroachdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: cockroachdb
    spec:
      containers:
        - args:
            - start-single-node
            - --insecure
            - --store=attrs=ssd,path=/var/lib/cockroach/
          image: cockroachdb/cockroach:latest-v20.2
          name: cockroachdb
          ports:
            - containerPort: 26257
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m" 
          volumeMounts:
            - mountPath: /var/lib/cockroach
              name: data
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
status: {}