apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nakama
  name: nakama
spec:
  ports:
    - name: "7349"
      port: 7349
      targetPort: 7349
    - name: "7350"
      port: 7350
      targetPort: 7350
    - name: "7351"
      port: 7351
      targetPort: 7351
    - name: "9100"
      port: 9100
      targetPort: 9100
  selector:
    io.kompose.service: nakama
status:
  loadBalancer: {}