name: 'terraform-init-fmt-plan-apply-by-tag'

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
      tags:
        description: 'Set terraform action: Apply / Destroy' 

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Select Terraform Action
        options: 
        - apply
        - destroy
      stack:
        type: choice
        description: Select Terraform Stack
        options: 
        - vpc
        - eks

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  AWS_REGION: ${{ secrets.aws_region }}
  base_working_directory: "devops/terraform/aws/nakama"
  # working-directory: "devops/terraform/aws/nakama"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix: { dir: ['devops/terraform/aws/nakama'] }

    defaults:
      run:
        shell: bash

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.action }} ${{ github.event.inputs.stack }}"" 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Check Terraform Version
      id: version
      run: terraform --version

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: "${{ env.base_working_directory }}${{  github.event.inputs.stack }}"

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      working-directory: "${{ env.base_working_directory }}${{  github.event.inputs.stack }}"

    - name: Terraform Plan
      id: plan
      run: terraform plan
      working-directory: "${{ env.base_working_directory }}${{  github.event.inputs.stack }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve
      working-directory: "${{ env.base_working_directory }}${{  github.event.inputs.stack }}"

    - name: Terraform destroy
      if: github.ref == 'refs/heads/master' && github.event.inputs.action == 'destroy'
      run: terraform destroy -auto-approve
      working-directory: "${{ env.base_working_directory }}${{  github.event.inputs.stack }}"
